### ISSUE TITLE
Error while installing pyaudio from ubuntu

### ISSUE THREAD

**Issue by Aleix20** [albertgubau/Nataly#9]
ERROR: Could not build wheels for pyaudio

**Comment by albertgubau** [comment]
Hi Aleix, try installing the following dependencies using this command:

`sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0`

Let me know if this works for you!

**Comment by Aleix20** [comment]
Hi Albert, that works 
Thank for your help
